### ISSUE TITLE
The MEDS v0.3 configuration interface being pursued in #55 is poor

### ISSUE THREAD

**Issue by mmcdermott** [mmcdermott/MEDS_Tabular_AutoML#74]
In particular, there is functionally no dependence on `MEDS_cohort_dir` in the later stages other than to infer other directories. Given that not all stages have the same interface, this duplicated parameter should be removed.

**Comment by Oufattole** [comment]
I think we can close this issue since we updated to using:
1. `input_dir` instead of MEDS_cohort_dir
2. `output_tabularized_dir` for the generated tabularized data.

See the config for tabularization [here](https://github.com/mmcdermott/MEDS_Tabular_AutoML/blob/07001be6eb15ec198961c4540172b36a4fed9d99/src/MEDS_tabular_automl/configs/tabularization.yaml#L9).
